### ISSUE TITLE
Fix site report references

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/supersead#81]

**Comment by johanvonboer** [comment]
More specifically: The reference column in the samples table in site reports is simply "null" since the db was changed regarding this. There is still some info showing up in the tooltips, but there is some fixing that needs to be done here.

**Comment by johanvonboer** [comment]
MAL data references are incomplete. Will be rendered properly when db is updated. References on the site level is now rendered as well.

**Comment by johanvonboer** [comment]
Print out "Author" instead of null

Example site: http://supersead.humlab.umu.se/site/2

**Comment by johanvonboer** [comment]
Add reference to dataset in the site references data boxes

**Comment by visead** [comment]
Illustration below.

The id for the main reference for any dataset is in tbl_datasets.biblio_id (this is the data source)

For the reports (landing pages) we should have two reference sections under the site info area (the first of which is most important):
Dataset reference
tbl_datasets.biblio_id
Site bibliography
tbl_site_references.biblio_id (potentially >1) and tbl_sample_group_references.biblio_id
 
Sites have their own references, in tbl_site_references, which connects site_id to one or more biblio_id, as do sample groups in tbl_sample_group_references
 
(Ideally we would have all of these in the same filter – SQL should exist for a view doing this from before, but it might be easier to make a new one. Love can help with this if needed. Something like select all biblio_id for tbl_site_references, tbl_sample_group_references, tbl_datasets where site_id = X)

![image](https://user-images.githubusercontent.com/35995002/77669386-f8472600-6f84-11ea-95bb-062464842575.png)

**Comment by johanvonboer** [comment]
Fixed

**Comment by visead** [comment]
The formatting of the reference is still not fixed - should be author, year, title (concatenated)

**Comment by johanvonboer** [comment]
Example references is now rendered as:
![image](https://user-images.githubusercontent.com/34707290/79852713-5110af80-83c7-11ea-82c1-c62d48164fc2.png)

The year is doubled because the title also contains the year, this is what the db data looks like:

[
  {
    "site_id": 2554,
    "authors": "Smith, D. N. (1999)",
    "date_updated": "2019-12-20T23:14:36.351+00:00",
    "doi": null,
    "isbn": null,
    "notes": null,
    "title": "Analysis of beetles in smoke blackened thatch. In. J. B. Letts (ed.) Smoke blackened thatch; a unique source of late medieval plant remains from southern England, 42-43. English Heritage & Reading University",
    "year": "1999"
  }
]
